# Generated by Django 4.2 on 2023-04-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_name',
            new_name='course_name',
        ),
    ]
