# Generated by Django 4.2 on 2023-05-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0003_alter_student_email_alter_student_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wireless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('ipaddress', models.CharField(max_length=200)),
                ('transportprotocol', models.CharField(max_length=100)),
            ],
        ),
    ]
